version: '3.8'

services:
  web:
    image: sapinspys/github_success_api
    build: 
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    expose:
      - 5000
    env_file:
      - ./.env.prod
